<?php
namespace framework\model;

use framework\base\Model;

class CommonLog extends Model
{
    private static $log_dsn = array(
        KEY_DSN_DB_TYPE  => 'mysql',
        KEY_DSN_HOST     => 'xxxx',
        KEY_DSN_PORT     => '3306',
        KEY_DSN_DB_NAME  => 'common_log',
        KEY_DSN_USERNAME => 'xxx',
        KEY_DSN_PASSWORD => 'xxxx',
        KEY_DSN_OPTION   => null,
    );

    public static function getInstance($dsn = null, $custom_cache_key = null)
    {
        return parent::getInstance(empty($dsn) === true ? self::$log_dsn : $dsn, $custom_cache_key); // TODO: Change the autogenerated stub
    }
}